### ISSUE TITLE
NVME booting

### ISSUE THREAD

**Issue by Johnnie390** [pipcet/pearl#10] opened 2021-08-15 11:10 UTC
Hello Pipcet,

is the above already implemented (internal or external) or do we have to wait?

Regards,

Ry

**Comment by yuyichao** [comment] 2021-08-15 13:20
I assume you mean to boot from the internal nvme as opposed to using an external usb drive? The Chinese article you linked uses an external usb drive but I believe it’s actually still booting from the nvme (the configure step copied the boot image over). The only difference is the location of the root file system. Using nvme for that also works but there are some sync issues (see my other issue)

 I basically used the old asahi installation instruction, not sure if there’s a more up to date process now.

**Comment by Johnnie390** [comment] 2021-08-15 14:02
"I assume you mean to boot from the internal nvme as opposed to using an external usb drive?" I was referring either to an external NVME SSD or indeed the inbuilt (Apple) NVME SSD.
The operational (Asahi/Corellium) documentation to achieve this is sparse, if at all.

Regards

Ry

**Comment by Johnnie390** [comment] 2021-08-16 18:19
Hello all,

any news/developments here?

Regards

Ry

**Comment by pipcet** [comment] 2021-08-16 18:25
Hello Ry,
not sure I understand correctly. I'm booting my M1 off the internal nvme with no external drive. Most others boot off external USB or just use an initrd at this point.

I'm currently working on making the pearl image use different devicetrees for Minis and MacBooks, so hopefully the hardware will work better for the Mini folks. Again, I don't have a Mini, so it's probably going to take a few test cycles before "everything" works.

Thanks again for wanting to test things at this early stage, and sorry it's probably going to involve more effort than you hoped it would. I understand perfectly well if you decide to leave things for the time being; like all software projects, this isn't as advanced as it should be at this point in time. That said, I have what I consider a fully-functioning desktop at this point, and I'll gladly help others get there, as well.

Pip

**Comment by Johnnie390** [comment] 2021-08-20 13:30
Afternoon Pipcet,

I have been travelling, hence the tardy reply.
As stated earlier, I have an M1 Mini (Mode A2348) and very much like shrink the Mackintosh partition and run a Debian Desktop.
Have you made any progress on producing a macho file for the M1 Mini yet?

Regards,

Ry

**Comment by pipcet** [comment] 2021-08-21 11:53
Hello Ry,
unfortunately, it turns out that USB host mode has been broken for some time.

There were two options, and I'm afraid I chose the wrong one:
* fix USB host mode by going back and bisecting to the last kernel version that worked, then figuring out how it broke
* use the Asahi Linux tree as a base, which I thought had working USB

I decided on the second approach, since it is something we're going to have to do at some point anyway.

What I did not realize at that point is just how much of the hardware initialization code had moved to m1n1.

Anyway, the current state is that with the new kernel I am testing, USB host mode works, but USB gadget mode and PCI are still mysteriously broken, and I need those for a usable system so I'll have to ask you for a bit more patience. I'll let you know once all three are working.

Thanks again, and sorry for the delay,
Pip

**Comment by pipcet** [comment] 2021-08-22 02:47
The good news is I am typing this on a USB keyboard, on the M1, so at least that part is working now. I've temporarily changed things so both Type-C ports are initialized for USB on all machines, though on the laptops it makes most sense to reserve one port for power, which currently means not enabling USB on it. (I understand the mini also has Type-A ports? I think those might not work right now)

The bad news is that there appears to be an unrelated bug in the `linux-next` kernel we're now based on, somehow related to `sys_shutdown`, which means it's not currently possible to open some sites in Firefox. I expect this to be fixed very soon, though, as it likely affects many more systems.

I'll push my tree now, and hopefully the release that will then happen automatically will work, but I won't be able to test it until what I gather is Sunday afternoon your time. I'll let you know when I have done so.

Thank you again for testing,
Pip

**Comment by Johnnie390** [comment] 2021-08-22 05:55
Thanks for the information Pip. Progress it seems.
My M1 Mini model (A2348) _does not_ have USB Type-A ports.
Looking forward to testing the macho file(s).

Regards,

Ry

**Comment by Johnnie390** [comment] 2021-08-22 06:53
Pip,
just tested Tag: 2021-08-22 · Commit: f695453. 
![Pearl-Boot-I](https://user-images.githubusercontent.com/22815859/130345572-af85c42d-6181-4273-94a7-9568fbc65255.jpg)
Results in a kernel panic unfortunately.

Regards,

Ry

**Comment by pipcet** [comment] 2021-08-22 09:03
Oh no, I'm sorry! I'd really hoped this would work right away. The problem is accessing the third PCI port, which might not be present or did not have its clocks enabled...

Uploading a version now which skips the problematic PCI port(s). I hope that will avoid the problem and allow you to get further, but I've also included extra code to print MMIO accesses as they happen.

**Comment by pipcet** [comment] 2021-08-23 03:33
I will get access to a mini very soon, so I can hopefully debug this more easily. I'll probably trigger a "release" (it's not really much of one without testing it first, is it?) before then, but I'll also let you know once I've actually tested on a mini.

**Comment by pipcet** [comment] 2021-12-18 17:35
Things work on a macOS 11 mini now, and are close to working on a macOS 12.1 mini. Closing for now.

**Closed by pipcet** 2021-12-18 17:35 UTC
